# This is a basic workflow that is manually triggered

name: DISC

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  CPU-TF115:
    uses: ./.github/workflows/cpu_reusable.yml
    with:
      remote_runtime_docker: bladedisc:latest-runtime-tensorflow1.15-cpu
      runtime_base_image: tensorflow/tensorflow:1.15.5
      exec_command: bash -c \
          "bash ./scripts/ci/build_and_test.sh --cpu-only && bash ./scripts/ci/test_tensorflow_blade.sh cpu 1.15"
      deploy_command: bash ./scripts/ci/deploy_tensorflow_blade.sh
    secrets:
      ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
      ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}