# This is a basic workflow that is manually triggered

name: DISC

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  CUDA10-TF115:
    if: github.repository == 'alibaba/BladeDISC'
    # The type of runner that the job will run on
    runs-on: [amd-gpu]


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout
      uses: actions/checkout@v2.4.0
    - name: pre-commit
      shell: bash
      run: |
        export PATH=$HOME/.local/bin:$PATH
        pre-commit run -a --show-diff-on-failure
    - name: Build Dev Docker
      shell: bash
      run: |
        set -e
        git submodule sync
        git submodule update --depth=1 --init --recursive
        docker build -t disc-dev-cuda10.0 \
          --build-arg HTTPS_PROXY=http://blade_disc:r299eNZXVTUpuyg7@8.217.91.10:12357 \
          --build-arg BASEIMAGE=nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04 \
          --build-arg DISC_HOST_TF_VERSION="tensorflow-gpu==1.15" \
          --build-arg DEVICE=cu100 \
          -f docker/dev/Dockerfile .