name: disc-build-pytorch1_8_1-gpu
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '30 01 * * *' # 01:30 am

jobs:
  cuda10_2-pytorch1_8_1:
    uses: ./.github/reusable/cuda_reusable.yml
    with:
      cuda_version: cu113
      remote_runtime_docker: bladedisc:latest-runtime-torch1.12.0-cu113
      develop_base_image: nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04
      runtime_base_image: nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04
      extra_build_args: --build-arg PYTHON_VERSION=PYTHON3.8 --build-arg ENABLE_FIND_FASTEST_APT_SOURCE=OFF
      extra_envs: -e TORCH_BLADE_BUILD_TENSORRT_STATIC=ON
          -e TORCH_BLADE_CI_BUILD_TORCH_VERSION=1.12.0+cu113
      exec_command: bash ./scripts/ci/test_pytorch_blade.sh
      deploy_command:  bash ./scripts/ci/deploy_pytorch_blade.sh
    secrets:
      ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
      ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}