name: disc-build-pytorch1_8_1-cpu
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '30 01 * * *' # 01:30 am

jobs:
  pytorch1_8_1:
    uses: ./.github/reusable/cpu_build.yml@${{ github.head_ref }}
    with:
      extra_envs: -e TORCH_BLADE_BUILD_WITH_CUDA_SUPPORT=OFF
        -e TORCH_BLADE_CI_BUILD_TORCH_VERSION=1.8.1+cpu
      exec_command: bash ./scripts/ci/test_pytorch_blade.sh
    secrets:
      ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
      ALIYUN_DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}